language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpcs --standard=PSR2 config && vendor/bin/phpcs --standard=PSR2 tests && vendor/bin/phpunit tests -v -c tests/phpunit.xml && vendor/bin/phpmd config,src,tests text cleancode,codesize,controversial,design,naming,unusedcode

after_success:
  - vendor/bin/test-reporter